### ISSUE TITLE
plotAVA is keeping the coords after cutPafAlignments

### ISSUE THREAD

**Issue by Rafaelsoler13** [daewoooo/SVbyEye#4]
Hello again,

I'm trying to cut a PAF file of the human chr8 at specific coordinates and plot it using _plotAVA_. However, when I select the coordinates and cut the PAF file with _cutPafAlignments_, I try to plot it with _plotAVA_ but it plots with the previous coordinates which are still selected. This does not happen with the _plotMiro_ function. Can you solve this with the _plotAVA_ function?

Thank you so much

**Full Human chr8**
![chr8_full](https://user-images.githubusercontent.com/51912958/233999724-0ac83719-2cf1-4ce8-8083-7fd939d76f59.jpeg)

**Human chr8 cut with AVA**
![chr8_cut_AVA](https://user-images.githubusercontent.com/51912958/233999721-446687b5-398d-4b33-bee8-399d878fa9d8.jpeg)

**Human chr8 cut with Miro**
![chr8_Miro](https://user-images.githubusercontent.com/51912958/233999713-339c667c-a02f-457c-b56d-595887dda158.jpeg)

**Comment by Rafaelsoler13** [comment]
Now plotMiro is not zooming also as plotAVA with the recent updates

**Comment by daewoooo** [comment]
Would be great to have an example code and input PAF so I can reproduce the error.

**Comment by daewoooo** [comment]
See example code below to solve your problem:
library(SVbyEye)

paf.table <- readPaf('chr8_test.paf.txt')
plotMiro(paf.table = paf.table)
paf.table.sub <- subsetPafAlignments(paf.table = paf.table, target.region = 'chr8:6000000-14000000')
plotMiro(paf.table = paf.table.sub)

To allow subsetting of all-vs-all alignments will be implemented later.

**Comment by gpreising** [comment]
Are there any plans to implement the subsetting of AVA alignments in the near future? Or is there a workaround that you've found that works for doing this? I'm trying to zoom in on a specific region of a 4-way alignment

**Comment by daewoooo** [comment]
To do this you would need to subset each FASTA to your region of interest and then create a 4-way alignment. Sorry didn't have a time yet to make subsetting working on all-versus-all alignments.

**Comment by gpreising** [comment]
No problem, that worked and then I fixed the coordinates in R. Thanks!
